language: scala

branches:
 only:
  - master

jdk:
 - openjdk7
scala:
 - 2.11.2

before_install:
 - chmod +x ./gradlew

install: true

script:
 - ./gradlew setupCIWorkspace
 - ./gradlew assemble

